# Generated by Django 4.1.5 on 2023-01-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Talcherdb',
            fields=[
                ('sn', models.IntegerField(db_column='Sn', primary_key=True, serialize=False)),
                ('task_name', models.TextField(blank=True, db_column='Task Name', null=True)),
                ('activity_type', models.TextField(blank=True, db_column='Activity Type', null=True)),
                ('planned_start', models.DateField(blank=True, db_column='Planned Start', null=True)),
                ('planned_finish', models.DateField(blank=True, db_column='Planned Finish', null=True)),
                ('actual_start', models.DateField(blank=True, db_column='Actual Start', null=True)),
                ('actual_finish', models.DateField(blank=True, db_column='Actual Finish', null=True)),
                ('pgma', models.TextField(blank=True, db_column='PGMA', null=True)),
                ('parent_wbs_level', models.TextField(blank=True, db_column='Parent WBS Level', null=True)),
            ],
            options={
                'db_table': 'talcherdb',
                'managed': False,
            },
        ),
    ]
